# AICP FIRST TASK

## IMPORT LIBRARIES

In [2]:
import numpy as np

# Write a NumPy program to create an array of all even integers from 30 to 70.


In [3]:
even_aaray1=np.arange(30,72,2)
even_aaray1

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.


In [4]:
random_numbers = np.random.randn(15)
print("Array of 15 random numbers from standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from standard normal distribution:
[ 1.24418936 -0.80964587  0.63307217  0.44963532  0.87613498 -0.7265905
 -0.62968854  0.07486996 -0.19266717 -0.30295783  0.50292575  0.8183978
  0.94276476 -1.65662318  1.370704  ]


# How to compute the cross-product of two matrices in NumPy?

In [5]:
matrix_1=np.matrix([[5, 6, 7], [4, 6,8]])
matrix_2=np.matrix([[34,6,8],[37,98,5]])
matrix_1


matrix([[5, 6, 7],
        [4, 6, 8]])

In [6]:
matrix_2

matrix([[34,  6,  8],
        [37, 98,  5]])

In [7]:
cross_product=np.cross(matrix_1,matrix_2)
cross_product

array([[   6,  198, -174],
       [-754,  276,  170]])

# How to compute the determinant of an array using NumPy?

In [8]:
array_1=np.array(([24,22,16,14], [88,6,4,9],[14,23,21,30], [100,54,32, 33]))
array_1

array([[ 24,  22,  16,  14],
       [ 88,   6,   4,   9],
       [ 14,  23,  21,  30],
       [100,  54,  32,  33]])

In [9]:
det_value = np.linalg.det(array_1)
det_value

-174040.0000000001

# How to create a 3x3x3 array with random values using NumPy?

In [10]:
array_3=array_3 = np.random.randn(3, 3, 3)
array_3

array([[[-1.19102102,  0.08050811,  1.1924023 ],
        [ 1.15043596,  0.23552575,  1.49812165],
        [-0.03784757,  1.01096734, -0.57191801]],

       [[ 0.07166154, -0.29568514, -1.54746193],
        [-1.12318596, -1.74277784, -0.44248282],
        [-1.20261463, -0.49400613, -0.92242648]],

       [[ 1.36062817,  0.75507628, -0.12426322],
        [ 0.66501917,  1.34665728, -0.00969413],
        [-0.70052843, -0.54728701, -0.40998784]]])

# How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?


In [11]:
array_5=array_3 = np.random.randn(5, 5)
array_5

array([[ 0.6227223 ,  0.47100833, -0.27086359,  0.42305009,  0.24739784],
       [-1.21412416, -1.43631226,  0.13299037,  0.52330009, -0.13956112],
       [ 0.19493195, -1.68576814,  0.2913981 ,  0.1893584 ,  0.38059684],
       [-0.17891532, -1.10737753,  1.47129722, -0.49950732, -1.21773301],
       [ 0.35442684,  0.66584437, -0.69430902,  1.17657344, -0.46602612]])

In [12]:
array_3.max()


1.471297220776394

In [13]:
array_3.min()

-1.6857681444905117

# How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [14]:
array_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
mean_values = np.mean(array_2d, axis=1)
std_dev_values = np.std(array_2d, axis=1)
variance_values = np.var(array_2d, axis=1)

print("Mean along the second axis:")
print(mean_values)

print("\nStandard Deviation along the second axis:")
print(std_dev_values)

print("\nVariance along the second axis:")
print(variance_values)

Mean along the second axis:
[2. 5. 8.]

Standard Deviation along the second axis:
[0.81649658 0.81649658 0.81649658]

Variance along the second axis:
[0.66666667 0.66666667 0.66666667]
